#!/usr/bin/env python3
import os
from sys import platform

def clear_screen():
    if platform == "linux" or platform == "linux2":
        os.system("clear")
    else:
        os.system("cls")
adb_command = ""
def set_commands():
    global adb_command
    if platform == "linux" or platform == "linux2":
        adb_command = "scripts/adb"
    else:
        adb_command = r".\scripts\adb.exe"
    global apk_path
    if platform == "linux" or platform == "linux2":
        apk_path = "apks/"
    else:
        apk_path = r"apks\"


set_commands()
os.system(f"{adb_command} kill-server")
clear_screen()
print("Make sure you have USB debugging enabled and authorize this PC by confirming on the pop up on your phone.")
os.system(f"{adb_command} start-server")
clear_screen()

first_time_check = input("Are you running this script for the first time on this device? (Y/N): ")
if first_time_check == "y" or first_time_check == "Y":
    print("Make sure your data is backed up, the phone is factory reset and connected to the computer via a USB cable and USB debugging is enabled.")
    input("Press ENTER to continue. This will start setting up your phone for the script (CTRL+C to cancel)...")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.aasaservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.setupwizard")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.restore")
    os.system(f"{adb_command} shell pm uninstall --user 0 android.auto_generated_rro_product__")
    os.system(f"{adb_command} shell pm uninstall --user 0 android.auto_generated_rro_vendor__")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.egg")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.configupdater")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.dsi.ant.sample.acquirechannels")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.dsi.ant.plugins.antplus")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.dsi.ant.service.socket")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mapsagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.ardrawing")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.arzone")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.ar.zone")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.spdfnote")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.hole")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.corner")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.autodoodle.service")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.dreams.basic")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.widgetapp.webmanual")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.motionphoto.viewer")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.visionintelligence")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixbyvision.framework")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.calllogbackup")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.factory.cameralyzer")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.chrome")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.chromecustomizations")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.cinnamon")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.circular.themepicker")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.circular.launcher")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.android")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.systemui")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.settings")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.backupconfirm")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.providers.partnerbookmarks")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.sharedstoragebackup")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.gsa")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.common")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.photos")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastreceiver")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wifi.recources")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wifi.softap.recources")
    os.system(f"{adb_command} shell pm uninstall --user 0 android.autoinstalls.config.samsung")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.homemode")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.livestickers")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.turbo")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.as")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.double")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.printspooler")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.tachyon")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.dreams.phototable")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.samsungapps")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.game.gametools")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.game.gamehome")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.gm")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.googlequicksearchbox")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.syncadapters.calendar")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.syncadapters.contacts")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.gms.location.history")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.onetimeinitializer")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.partnersetup")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.carrier.carrierwifi")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.green")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mobileservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.dynamiclock")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.hiya.star")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.tall")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.klmsagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.knox.analytics.uploader")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.simplesharing")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.livedrawing")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.maps")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdx.quickboard")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdx.kit")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdx")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.facebook.katana")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.facebook.services")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.facebook.system")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.facebook.appmanager")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.netflix.mediaclient")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.cellbroadcastreceiver")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.cellbroadcastservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.netflix.partner.activation")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.font.notoserifsource")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.ocean")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.microsoft.skydrive")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.microsoft.appmanager")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.orchid")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.pebble")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.peoplestripe")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.printservice.recommendation")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.purple")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.ringtoneBR")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.launcher")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.systemui")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.themepicker")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.settings")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.android")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.roundedrect")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.svoiceime")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.feedback")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.smartswitchassistant")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.osp.app.signin")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.desktopmode.uiservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.spage")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.kidsinstaller")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.spp.push")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.smartsuggestions")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sm.policy")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.cocktailbarservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.appseparation")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.location.nfwlocationprivacy")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.setupwizardlegalprovider")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.knox.securefolder")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.fast")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.location")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.smartcallprovider")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.easyMover.Agent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.stplatform")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.smartmirroring")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.space")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.aircommand")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.squircle")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.bips")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.easysetup")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.mainline.telemetry")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.traceur")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.desktopsystemui")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.systemui.bixby2")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.accessibility.talkback")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.icecone")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.taskedge")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.taperedrect")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.teardrop")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.tips")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.pentastic")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.airviewdictionary")
    os.system(f"{adb_command} shell pm uninstall --user 0 de.axelspringer.yana.zeropage")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.vessel")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.watchmanagerstub")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.diotek.sec.lookup.dictionary")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.youtube")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.clipboardedge")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdecservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.preloadinstaller")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.waterfall")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixby.service ")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixby.agent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixby.agent.dummy")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixby.wakeup")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.callbgprovider")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.clipboardsaveservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.wallpaperbackup")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.factory")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.diagmonagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.dynsystem")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.aircommandmanager")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.factory.camera")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.fmm")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.fm")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.themestore")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.themecenter")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.storyservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sm.devicesecurity")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.gpuwatchapp")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.providers.carrier")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.omcagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sdm.config")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.allshare.service.fileshare")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.allshare.service.mediashare")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.rubin.app")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.aware.service")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.sharelive")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.scloud")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.desktoplauncher")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.SecSetupWizard")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.location.nsflp2")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.securitylogagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.settings.bixby")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.shortcutbackupservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.skms.android.agent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.beaconmanager")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.soagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.wssyncmldm")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.stickercenter")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.systemupdate")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.quicktool")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.wlantest")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.aremoji")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.aremojieditor")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.mimage.avatarstickers")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.authfw")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.samsungpass")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.samsungpassautofill")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.nfc ")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.stk ")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.stk2")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.da.daagent ")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.vtcamerasettings")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.apex")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.ipsgeofence")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.samsungpositioning")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload ")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.incall.contentprovider")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.unifiedwfc")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.stickercenter")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.visualars")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.projection.gearhead")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.privateshare")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mateagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.routines")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.tagservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.apps.tag")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sdk.handwriting")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.magnifier")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.vending")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.reminder")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.setupwizard.searchselector")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.ve.vebgm")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.knox.containeragent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.knox.containercore")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.managedprovisioning")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.bookmarkprovider")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.epdgtestapp")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.setting.multisound")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.smartcapture")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.providers.userdictionary")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.ledbackcover")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.forest")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.applinker")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.adaptivebrightnessgo")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.bcservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.mhs.smarttethering")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.networkdiagnostic")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sume.snn.service")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sume.nn.service")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.tadownloader")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.brightnessbackupservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.server.wifi.mobilewips")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sem.factoryapp")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.svcagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.automation")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.DataCreate")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.easyonehand")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.safetyassurance")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.sve")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.personalization")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.bluetoothtest")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.sec.android.application.csc")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bbc.bbcagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.tapack.authfw")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.provider.badge")
    os.system(f"{adb_command} shell pm disable-user com.google.ar.core")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.provider.emergencymode")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.carrierdefaultapp")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.emergency")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.safetyinformation")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.hdmapp")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.notes")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.notes.addons")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.htmlviewer")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.updatecenter")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.as.oss")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.wallpaper.livepicker")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.tapack.authfw")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.cameraextensions")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.wallpapercropper")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.providers.factory")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.gru ")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.singletake.service")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.vsim.ericssonnsds.webapp")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.systemui.onehanded.gestural")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.providers.downloads.ui ")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.dofviewer")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mcfds")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.cidmanager")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.app.RilErrorNotifier")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.rcs ")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.monotype.android.font.foundation")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.monotype.android.font.samsungone")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.messaging")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.dialer")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.calendar")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.contacts")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.myfiles")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.dialer")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.camerasdkservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.cameraxservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.gallery3d")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.camera")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.mimage.photoretouching")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.spayfw")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.lool")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.video")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wallpaper.res")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.galaxyfinder")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.incallui")
    os.system(f"{adb_command} shell pm disable-user com.samsung.android.honeyboard")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.app.newtrim")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.clockpackage")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.daemonapp")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_wide_back")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_extra_wide_back")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_narrow_back")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.networkstack.tethering.overlay")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wifi.softap.resources")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wifi.resources")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.phone.overlay.common")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.ConnectivityOverlay")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.ConnectivityUxOverlay")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.container")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.dsms")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.vepreload")
    os.system(f"{adb_command} shell pm disable-user com.samsung.android.game.gos")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.statementservice")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.knox.kpecore")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.storagemanager")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdm")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdagent")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.companiondevicemanager")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.soundalive")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.networkstack")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.billing")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mcfserver")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wcmurlsnetworkstack")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.wsomacp")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.cmfa.AuthTouch")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.cmfa.AuthTouch")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.cmfa.framework")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.android.ons")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.epdg")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.cmh")
    os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.hearingadjust")
elif first_time_check == "n" or first_time_check == "N":
    clear_screen()
else:
    print("Invalid input.")
    exit()

def main_menu():
    clear_screen()
    global i
    print("One UI Experience - Optimization tool for Samsung Phones running\nAndroid 11 or 12 by Jan Biernacik")
    print("-----------------------------------------------------------------------")
    print("Main options:")
    print("[1] One UI Preset")
    print("[2] Google Preset (minimal)")
    print("[3] AOSP Preset (stockish android)")
    print("Advanced options:")
    print("[4] Fuckin kim jong un style debloat (you will be left with a settings app nothing else, just like the pre-setup preset.)")
    print("[5] Restore updates")
    print("[6] Restore basic Android features (printing, nfc, screen saver etc.)")
    print("[7] Restore Play Store (AOSP preset)")
    print("[8] Restore Samsung account (AOSP, Google preset)")
    print("[8] Restore Samsung bloatware")
    print("Other:")
    print("[10] Restore custom package")
    print("[11] Remove custom package")
    print("Program:")
    print("[12] Exit")

    selection = int(input("\n\nPlease make a selection: "))
    if selection == 1:
        print("One UI preset will be applied to your phone.")
        os.system(f"{adb_command} shell pm enable com.samsung.android.honeyboard")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.dialer")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.messaging")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.app.contacts")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.calendar")
        os.system(f"{adb_command} shell pm install-existing com.sec.hearingadjust")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.vepreload")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.incallui")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.lool")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.forest")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.app.galaxyfinder")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.camera")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.gallery3d")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.mimage.photoretouching")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.myfiles")
        os.system(f"{adb_command} shell pm install-existing com.samsung.rcs")
        os.system(f"{adb_command} shell pm install-existing com.osp.app.signin")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.mdx.kit")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.aware.service")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.app.sharelive")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.allshare.service.mediashare")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.allshare.service.fileshare")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.soundalive")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.singletake.service")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.app.notes")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.app.smartcapture")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.service.airviewdictionary")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.service.pentastic")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.service.aircommand")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.aircommandmanager")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.video")
        os.system(f"{adb_command} shell pm install-existing com.samsung.app.newtrim")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.mdx.quickboard")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.daemonapp")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.clockpackage")
        os.system(f"{adb_command} shell pm install-existing com.samsung.klmsagent")
        os.system(f"{adb_command} shell pm install-existing com.android.vending")
        fortnite = input("Press ENTER to continue...")
    elif selection == 2:
        print("Google preset will be applied to your phone.")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.vepreload")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.camera")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.gallery3d")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.mimage.photoretouching")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.video")
        os.system(f"{adb_command} shell pm install-existing com.samsung.app.newtrim")
        os.system(f"{adb_command} shell pm install-existing com.sec.hearingadjust")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.lool")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.app.galaxyfinder")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.allshare.service.mediashare")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.allshare.service.fileshare")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.soundalive")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.aircommandmanager")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.mdx.quickboard")
        os.system(f"{adb_command} shell pm install-existing com.android.vending")
        os.system(f"{adb_command} shell pm install-existing com.android.chrome")
        os.system(f"{adb_command} shell pm install-existing com.google.android.apps.photos")
        os.system(f"{adb_command} shell pm install-existing com.google.android.apps.messaging")
        os.system(f"{adb_command} shell pm install-existing com.google.android.syncadapters.calendar")
        os.system(f"{adb_command} shell pm install-existing com.google.android.syncadapters.contacts")
        os.system(f"{adb_command} install {apk_path}g_clock.apk")
        os.system(f"{adb_command} install {apk_path}g_calendar.apk")
        os.system(f"{adb_command} install {apk_path}g_contacts.apk")
        os.system(f"{adb_command} install {apk_path}g_dialer.apk")
        os.system(f"{adb_command} install {apk_path}files.apk")
        os.system(f"{adb_command} install {apk_path}gboard.apk")
        os.system(f"{adb_command} install {apk_path}recorder.apk")
        fortnite = input("Press ENTER to continue...")
    elif selection == 3:
        print("AOSP preset will be applied to your phone (note that it will still look like One UI)")
        os.system(f"{adb_command} shell pm enable com.samsung.android.honeyboard")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.vepreload")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.camera")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.gallery3d")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.mimage.photoretouching")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.video")
        os.system(f"{adb_command} shell pm install-existing com.samsung.app.newtrim")
        os.system(f"{adb_command} shell pm install-existing com.sec.hearingadjust")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.lool")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.app.galaxyfinder")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.allshare.service.mediashare")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.allshare.service.fileshare")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.app.soundalive")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.aircommandmanager")
        os.system(f"{adb_command} shell pm install-existing com.samsung.android.mdx.quickboard")
        os.system(f"{adb_command} install {apk_path}aosp_clock.apk")
        os.system(f"{adb_command} install {apk_path}aosp_calendar.apk")
        os.system(f"{adb_command} install {apk_path}aosp_contacts.apk")
        os.system(f"{adb_command} install {apk_path}aosp_messages.apk")
        os.system(f"{adb_command} install {apk_path}aosp_dialer.apk")
        os.system(f"{adb_command} install {apk_path}files.apk")
        os.system(f"{adb_command} install {apk_path}fdroid.apk")
        os.system(f"{adb_command} install {apk_path}recorder.apk")
        fortnite = input("Press ENTER to continue...")
    elif selection == 4:
        print("Nuking yo fuckin' phone")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.aasaservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.setupwizard")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.restore")
        os.system(f"{adb_command} shell pm uninstall --user 0 android.auto_generated_rro_product__")
        os.system(f"{adb_command} shell pm uninstall --user 0 android.auto_generated_rro_vendor__")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.egg")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.configupdater")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.dsi.ant.sample.acquirechannels")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.dsi.ant.plugins.antplus")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.dsi.ant.service.socket")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mapsagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.ardrawing")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.arzone")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.ar.zone")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.spdfnote")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.hole")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.corner")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.autodoodle.service")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.dreams.basic")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.widgetapp.webmanual")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.motionphoto.viewer")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.visionintelligence")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixbyvision.framework")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.calllogbackup")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.factory.cameralyzer")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.chrome")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.chromecustomizations")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.cinnamon")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.circular.themepicker")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.circular.launcher")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.android")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.systemui")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.settings")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.backupconfirm")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.providers.partnerbookmarks")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.sharedstoragebackup")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.gsa")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.common")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.photos")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastreceiver")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wifi.recources")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wifi.softap.recources")
        os.system(f"{adb_command} shell pm uninstall --user 0 android.autoinstalls.config.samsung")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.homemode")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.livestickers")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.turbo")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.as")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.double")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.printspooler")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.tachyon")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.dreams.phototable")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.samsungapps")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.game.gametools")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.game.gamehome")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.gm")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.googlequicksearchbox")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.syncadapters.calendar")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.syncadapters.contacts")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.gms.location.history")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.onetimeinitializer")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.partnersetup")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.carrier.carrierwifi")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.green")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mobileservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.dynamiclock")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.hiya.star")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.tall")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.klmsagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.knox.analytics.uploader")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.simplesharing")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.livedrawing")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.maps")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdx.quickboard")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdx.kit")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdx")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.facebook.katana")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.facebook.services")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.facebook.system")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.facebook.appmanager")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.netflix.mediaclient")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.cellbroadcastreceiver")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.cellbroadcastservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.netflix.partner.activation")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.font.notoserifsource")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.ocean")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.microsoft.skydrive")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.microsoft.appmanager")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.orchid")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.pebble")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.peoplestripe")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.printservice.recommendation")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.purple")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.ringtoneBR")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.launcher")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.systemui")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.themepicker")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.settings")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.android")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.roundedrect")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.svoiceime")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.feedback")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.smartswitchassistant")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.osp.app.signin")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.desktopmode.uiservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.spage")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.kidsinstaller")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.spp.push")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.smartsuggestions")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sm.policy")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.cocktailbarservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.appseparation")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.location.nfwlocationprivacy")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.setupwizardlegalprovider")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.knox.securefolder")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.fast")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.location")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.smartcallprovider")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.easyMover.Agent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.stplatform")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.smartmirroring")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.color.space")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.aircommand")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.squircle")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.bips")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.easysetup")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.mainline.telemetry")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.traceur")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.desktopsystemui")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.systemui.bixby2")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.accessibility.talkback")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.icecone")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.taskedge")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.taperedrect")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.teardrop")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.tips")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.pentastic")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.airviewdictionary")
        os.system(f"{adb_command} shell pm uninstall --user 0 de.axelspringer.yana.zeropage")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.theme.icon.vessel")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.watchmanagerstub")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.diotek.sec.lookup.dictionary")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.youtube")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.clipboardedge")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdecservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.preloadinstaller")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.waterfall")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixby.service ")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixby.agent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixby.agent.dummy")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bixby.wakeup")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.callbgprovider")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.clipboardsaveservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.wallpaperbackup")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.factory")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.diagmonagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.dynsystem")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.aircommandmanager")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.factory.camera")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.fmm")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.fm")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.themestore")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.themecenter")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.storyservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sm.devicesecurity")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.gpuwatchapp")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.providers.carrier")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.omcagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sdm.config")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.allshare.service.fileshare")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.allshare.service.mediashare")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.rubin.app")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.aware.service")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.sharelive")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.scloud")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.desktoplauncher")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.SecSetupWizard")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.location.nsflp2")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.securitylogagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.settings.bixby")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.shortcutbackupservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.skms.android.agent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.beaconmanager")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.soagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.wssyncmldm")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.stickercenter")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.systemupdate")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.quicktool")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.wlantest")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.aremoji")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.aremojieditor")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.mimage.avatarstickers")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.authfw")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.samsungpass")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.samsungpassautofill")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.nfc ")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.stk ")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.stk2")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.da.daagent ")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.vtcamerasettings")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.apex")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.ipsgeofence")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.samsungpositioning")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload ")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.incall.contentprovider")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.unifiedwfc")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.stickercenter")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.visualars")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.projection.gearhead")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.privateshare")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mateagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.routines")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.service.tagservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.apps.tag")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sdk.handwriting")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.magnifier")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.vending")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.reminder")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.apps.setupwizard.searchselector")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.ve.vebgm")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.knox.containeragent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.knox.containercore")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.managedprovisioning")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.bookmarkprovider")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.epdgtestapp")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.setting.multisound")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.smartcapture")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.providers.userdictionary")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.ledbackcover")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.forest")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.applinker")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.adaptivebrightnessgo")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.bcservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.mhs.smarttethering")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.networkdiagnostic")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sume.snn.service")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.sume.nn.service")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.tadownloader")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.brightnessbackupservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.server.wifi.mobilewips")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sem.factoryapp")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.svcagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.automation")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.DataCreate")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.easyonehand")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.safetyassurance")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.sve")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.personalization")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.bluetoothtest")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.sec.android.application.csc")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.bbc.bbcagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.tapack.authfw")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.provider.badge")
        os.system(f"{adb_command} shell pm disable-user com.google.ar.core")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.provider.emergencymode")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.carrierdefaultapp")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.emergency")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.safetyinformation")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.hdmapp")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.notes")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.notes.addons")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.htmlviewer")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.updatecenter")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.google.android.as.oss")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.wallpaper.livepicker")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.tapack.authfw")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.cameraextensions")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.wallpapercropper")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.providers.factory")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.gru ")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.singletake.service")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.vsim.ericssonnsds.webapp")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.systemui.onehanded.gestural")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.providers.downloads.ui ")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.dofviewer")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mcfds")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.cidmanager")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.app.RilErrorNotifier")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.rcs ")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.monotype.android.font.foundation")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.monotype.android.font.samsungone")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.messaging")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.dialer")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.calendar")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.contacts")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.myfiles")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.dialer")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.camerasdkservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.cameraxservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.gallery3d")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.camera")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.mimage.photoretouching")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.spayfw")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.lool")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.video")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wallpaper.res")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.app.galaxyfinder")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.incallui")
        os.system(f"{adb_command} shell pm disable-user com.samsung.android.honeyboard")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.app.newtrim")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.clockpackage")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.daemonapp")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_wide_back")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_extra_wide_back")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_narrow_back")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.networkstack.tethering.overlay")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wifi.softap.resources")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wifi.resources")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.phone.overlay.common")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.ConnectivityOverlay")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.ConnectivityUxOverlay")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.container")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.dsms")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.vepreload")
        os.system(f"{adb_command} shell pm disable-user com.samsung.android.game.gos")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.statementservice")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.knox.kpecore")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.storagemanager")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdm")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mdagent")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.companiondevicemanager")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.soundalive")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.networkstack")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.android.app.billing")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.mcfserver")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.wcmurlsnetworkstack")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.wsomacp")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.cmfa.AuthTouch")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.cmfa.AuthTouch")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.android.cmfa.framework")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.android.ons")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.epdg")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.samsung.cmh")
        os.system(f"{adb_command} shell pm uninstall --user 0 com.sec.hearingadjust")
        os.system(f"{adb_command} shell settings put global window_animation_scale 0.80")
        os.system(f"{adb_command} shell settings put global transition_animation_scale 0.90")
        os.system(f"{adb_command} shell settings put global animator_duration_scale 1.25")
        fortnite = input("Press ENTER to continue...")
    elif selection == 5:
        print("Restoring updates...")
        os.system(f"{adb_command} shell pm install-existing com.wssyncmldm")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.soagent")
        os.system(f"{adb_command} shell pm install-existing com.sec.android.systemupdate")
        fortnite = input("Press ENTER to continue...")
    elif selection == 6:
        print("Restoring basic Android features...")
        os.system(f"{adb_command} shell pm install-existing com.android.bips")
        os.system(f"{adb_command} shell pm install-existing com.android.printspooler")
        os.system(f"{adb_command} shell pm install-existing com.android.htmlviewer")
        os.system(f"{adb_command} shell pm install-existing com.android.nfc")
        os.system(f"{adb_command} shell pm install-existing com.android.dreams.basic")
        os.system(f"{adb_command} shell pm install-existing com.android.dreams.phototable")
        fortnite = input("Press ENTER to continue...")
    elif selection == 7:
        print("Restoring play store (AOSP)...")
        os.system(f"{adb_command} shell pm install-existing com.android.vending")
        fortnite = input("Press ENTER to continue...")
    elif selection == 8:
        print("Restoring Samsung account (AOSP, Google preset)...")
        os.system(f"{adb_command} shell pm install-existing com.osp.app.signin")
        os.system(f"{adb_command} shell pm install-existing com.samsung.klmsagent")
        fortnite = input("Press ENTER to continue...")
    elif selection == 9:
        print("Restoring Samsung bloaware")
        print("Coming soon.")
        fortnite = input("Press ENTER to continue...")
    elif selection == 10:
        to_restore = input("Enter a package to restore: ")
        os.system(f"{adb_command} shell pm install-existing {to_restore}")
        fortnite = input("Press ENTER to continue...")
    elif selection == 11:
        to_remove = input("Enter a package to remove: ")
        os.system(f"{adb_command} shell pm uninstall --user 0 {to_remove}")
        fortnite = input("Press ENTER to continue...")
    elif selection == 12:
        i = 0
    else:
        print("Not a valid selection.")
        exit()

i = 1
while i == 1:
    main_menu()
